### PR TITLE
Add link to reference docs in README

### PR DESCRIPTION
**Pull request by Leo-Ryu**

### CODE REVIEW

**Comment by Leo-Ryu** [comment]
Would it be helpful if I migrated over parts of the README to a userguide document in the docs?

**Comment by Leo-Ryu** [comment]
@alexprengere Besides the reference docs, is there anything at all you'd like to have in the docs? I'll tailor them to your needs

**Comment by alexprengere** [comment]
The [rendered README](https://docs.contour.so/alexprengere/currencyconverter/README) seems to not interpret rst directives (code-block mostly). If there is a way to fix this, then this should be the default url the link points to. Then I believe this is good enough to be merged. For now reference docs and the README are a good starting point.

**Comment by Leo-Ryu** [comment]
@alexprengere README now rendered and https://docs.contour.so/alexprengere/currencyconverter/README is the default link to documentation-- let me know if there's anything else!

**Comment by TimothyWang56** [comment]
@alexprengere 
Hi there, and happy holidays! I'm Tim, a student at Brown University, working on this documentation platform with @Leo-Ryu. We're really interested in improving the platform and building it out based on user-feedback, and would appreciate any feedback you might have after having it merged in for a little over a week. Feel free to reach out with any thoughts/critiques!

**Pull request merged**
